use base64::Engine as _;
use tauri::{AppHandle, Manager};

/// One-way PowerPoint export helper: writes generated bytes to the
/// user's Downloads folder and returns the final path, so the frontend
/// can open it with the default app (PowerPoint) via plugin-opener.
///
/// Filenames arrive pre-slugged from the frontend (`my-sermon.pptx`);
/// path separators are rejected defensively, and collisions get
/// `name (2).pptx` suffixes — the returned path is always the file
/// that was actually written.
#[tauri::command]
pub fn save_export(
    app: AppHandle,
    file_name: String,
    base64_data: String,
) -> Result<String, String> {
    if file_name.is_empty()
        || file_name.contains('/')
        || file_name.contains('\\')
        || file_name.contains("..")
    {
        return Err("Refused unsafe export filename.".into());
    }
    let dir = app
        .path()
        .download_dir()
        .map_err(|e| format!("No download folder: {e}"))?;
    let bytes = base64::engine::general_purpose::STANDARD
        .decode(base64_data.as_bytes())
        .map_err(|e| format!("Bad export payload: {e}"))?;

    let (stem, ext) = match file_name.rsplit_once('.') {
        Some((stem, ext)) => (stem.to_string(), format!(".{ext}")),
        None => (file_name.clone(), String::new()),
    };
    let mut candidate = dir.join(format!("{stem}{ext}"));
    let mut counter = 2;
    while candidate.exists() {
        candidate = dir.join(format!("{stem} ({counter}){ext}"));
        counter += 1;
    }
    std::fs::write(&candidate, bytes)
        .map_err(|e| format!("Could not write export: {e}"))?;
    candidate
        .to_str()
        .map(str::to_string)
        .ok_or_else(|| "Export path is not valid unicode.".to_string())
}
